apiVersion: v1
kind: Service
metadata:
  name: express-backend-svc
  namespace: k8s-demo
spec:
  selector:
    app: express-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30080
